[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.0.1",
    "ruff>=0.8.6",
    "virtualenv>=20.28.1",
]
[tool.uv]
package = false
